# Generated by Django 2.2.6 on 2019-10-28 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contest",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("region", models.CharField(max_length=50)),
                ("city", models.CharField(max_length=50)),
                (
                    "contest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vkoshp.Contest"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                (
                    "medal",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("n", "none"),
                            ("g", "gold"),
                            ("s", "silver"),
                            ("b", "bronse"),
                        ],
                        default="n",
                        max_length=1,
                    ),
                ),
                ("codeforces_handle", models.CharField(default="", max_length=50)),
                ("codeforces_rating", models.PositiveIntegerField(default=0)),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="vkoshp.Team"
                    ),
                ),
            ],
        ),
    ]
